// Maps ZMK Swedish locale key constants (from keys_sv.h) to display symbols.
module.exports = {
  SV_A_UMLAUT:    'Ä',
  SV_O_UMLAUT:    'Ö',
  SV_A_RING:      'Å',
  SV_P:           'P',
  SV_AT:          '@',
  SV_EXCL:        '!',
  SV_AMPS:        '&',
  SV_DLLR:        '$',
  SV_SLASH:       '/',
  SV_FSLH:        '/',
  SV_MINUS:       '-',
  SV_PLUS:        '+',
  SV_STAR:        '*',
  SV_HASH:        '#',
  SV_QMARK:       '?',
  SV_PRCNT:       '%',
  SV_EQUAL:       '=',
  SV_LPAR:        '(',
  SV_RPAR:        ')',
  SV_LT:          '<',
  SV_GT:          '>',
  SV_ACUTE:       '´',
  SV_TILDE:       '~',
  SV_CARET:       '^',
  SV_SECT:        '§',
  SV_SINGLE_QUOTE:"'",
  SV_DQT:         '"',
  SV_N0: '0', SV_N1: '1', SV_N2: '2', SV_N3: '3', SV_N4: '4',
  SV_N5: '5', SV_N6: '6', SV_N7: '7', SV_N8: '8', SV_N9: '9',
};
